//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForPasha {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForPasha.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INTRO-F1:CHOISE-KG1-F1
        ///CHOISE-KG1-F1:осмотреть каюту гибернации_KG2-F1;выйти в коридор_CORRIDOR-GB-LZ-F1
        ///CORRIDOR-GB-LZ-F1:CHOISE-LZ1-F1
        ///CHOISE-LZ1-F1:дверь слева_CORRIDOR-LZ-NV-F1;дверь напротив_CORRIDOR-LZ-CS3-F1(KG2-F1)_NO-1(LZ-AD1-F1,LZ-AD3-F1,LZ-AD4-F1)_CORRIDOR-LZ-CS2-F1;вернуться в каюту гибернации_NO-1(KG2-F1)_CORRIDOR3-LZ-GB-F1
        ///CORRIDOR3-LZ-GB-F1:CHOISE-KG1-F1
        ///KG2-F1:CORRIDOR2-GB-LZ-F1
        ///CORRIDOR2-GB-LZ-F1:CHOISE-LZ1-F1
        ///CORRIDOR-LZ-CS3-F1:CHOISE-C2-LZ-CS-F1
        ///CHOISE-C2-LZ-CS-F1:осмотреть коридо [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
